name: php-pear
profiles:
  php56w:
    define:
      php_name: php56w
  php70w:
    define:
      php_name: php70w
  php71w:
    define:
      php_name: php71w
  php72w:
    define:
      php_name: php72w
builds:
  webtatic-el7:
    target: el7-development
    arch: [x86_64]
    profiles:
      - php56w
      - php70w
      - php71w
      - php72w
  webtatic-el6:
    target: el6-development
    arch: [x86_64, i386]
    profiles:
      - php56w
      - php70w
      - php71w
