name: php-pear
profiles:
  php54w:
    define:
      php_name: php54w
  php55w:
    define:
      php_name: php55w
  php56w:
    define:
      php_name: php56w
  php70w:
    define:
      php_name: php70w
builds:
  webtatic-el7:
    target: el7-development
    arch: [x86_64]
    profiles:
      - php54w
      - php55w
      - php56w
      - php70w
  webtatic-el6:
    target: el6-development
    arch: [x86_64, i386]
    profiles:
      - php54w
      - php55w
      - php56w
      - php70w
  webtatic-el5:
    target: el6-development
    arch: [x86_64, i386]
    profiles:
      - php54w
      - php55w
